version: "3.9"
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    command: >
      postgres
      -c log_statement=all
      -c log_duration=on
      -c logging_collector=off
      -c log_destination=stderr

volumes:
  db-data:
