import Spacer from "@/components/Spacer";
import { PageTitle, Wrapper } from "./styles";

export default function Home() {
  return (
    <Wrapper>
      <PageTitle>Home</PageTitle>
      <Spacer size={16} />
      <p>
        Welcome to the <strong>School Portal</strong>, a modern web application
        designed to simplify student and class management. This platform offers
        a clean interface for browsing, adding, and updating student records.
        With a focus on usability, the app ensures that users can quickly find
        and organize information. Whether you&apos;re an educator or a
        developer, you&apos;ll find the experience intuitive and efficient.
        It&apos;s a great starting point for learning how to build robust,
        data-driven interfaces.
      </p>
      <Spacer size={16} />

      <p>
        This project is built using <strong>GraphQL</strong> and{" "}
        <strong>Prisma</strong>, providing a powerful combination for querying
        and managing data. Features like *cursor-based pagination*, dynamic
        sorting, and nested field resolution help simulate real-world backend
        challenges. The underlying architecture demonstrates patterns like
        resolver composition, batching, and data loading. These techniques
        ensure the app scales well as data complexity grows. It&apos;s not just
        functional—it&apos;s also a learning resource.
      </p>
      <Spacer size={16} />

      <p>
        You can explore the <strong>Students</strong> section to view a live
        grid of student profiles, complete with class details and age filters.
        Every student is linked to their class, which is resolved efficiently to
        avoid the common N+1 query problem. Updates are reflected instantly,
        making it easy to test out mutations and data changes. The interface is
        responsive and clean, making it suitable for both desktop and mobile
        viewing. There&apos;s also potential to extend this with features like
        student avatars, class schedules, and attendance tracking.
      </p>
      <Spacer size={16} />

      <p>
        If you&apos;re curious about the technologies or the development
        process, head over to the <strong>About</strong> page. There,
        you&apos;ll find a breakdown of the stack, design goals, and how ChatGPT
        was used to accelerate development. This project was built with{" "}
        <em>performance</em>, <em>clarity</em>, and{" "}
        <em>developer experience</em> in mind. We hope it serves as both a
        helpful tool and an inspiring example. Happy exploring!
      </p>
      <Spacer size={16} />

      <p style={{ fontStyle: "italic", fontSize: "0.9em" }}>
        (All content on this page was generated by ChatGPT.)
      </p>
    </Wrapper>
  );
}
