import Spacer from "@/components/Spacer";
import { Wrapper } from "./styles";
import { PageTitle } from "../styles";

function AboutPage() {
  return (
    <Wrapper>
      <PageTitle>About</PageTitle>
      <Spacer size={16} />
      <p>
        Welcome to our School Portal — a modern and intuitive web application
        designed to streamline student information management and enhance
        collaboration across the educational community. Whether you&apos;re a student
        eager to explore your academic progress, a teacher managing multiple
        classes, or an administrator overseeing the entire system, this portal
        is built with you in mind.
      </p>
      <Spacer size={16} />

      <p>
        At the heart of the platform lies a robust system that connects students
        with their classes, tracks academic performance, and allows for seamless
        updates. The clean and responsive interface ensures that everyone,
        regardless of technical background, can navigate the platform with ease.
      </p>
      <Spacer size={16} />

      <p>
        Features include real-time student listings with powerful filters and
        sorting, support for pagination and efficient data loading, and a
        dedicated profile system for students. Every piece of data is securely
        managed, ensuring privacy and compliance with educational standards.
      </p>
      <Spacer size={16} />

      <p>
        Our application was built with modern web technologies including
        GraphQL, Apollo Client, Prisma, and PostgreSQL. We believe that powerful
        tools should enable simple, meaningful experiences — and this portal
        reflects that philosophy.
      </p>
      <Spacer size={16} />

      <p>
        This project is also a technical showcase. From implementing
        cursor-based pagination to optimizing backend performance with batching
        strategies and DataLoader, the development process reflects best
        practices and thoughtful design choices.
      </p>
      <Spacer size={16} />

      <p>
        Whether you&apos;re browsing through a gallery of students, searching by
        class, or learning more about how the system works, we hope you enjoy
        using this application as much as we enjoyed building it.
      </p>
      <Spacer size={16} />

      <p style={{ fontStyle: "italic", fontSize: "0.9em" }}>
        (All content on this page was generated by ChatGPT.)
      </p>
    </Wrapper>
  );
}

export default AboutPage;
